### ISSUE TITLE
Add event tags

### ISSUE THREAD

**Issue by hyperupcall** [hackclub/events#13]
Hai,

I think it would be super useful to have the ability to tag events, for example "chess", "ctf", "ama", "minecraft", "community", etc. Later maybe we can even show event history with tag filtering

Would this be something we would implement with airtable or the hackclub v2 api (located in a different repository) first - before rendering it properly using code in this repo? I'm not quite sure - i can definitely make a PR though :)

**Comment by lachlanjc** [comment]
@eankeen Go for it! We’ve added a new `Tags` field on events & tagged nearly everything in our database. https://airbridge.hackclub.com/v0.1/Sessions/Events

**Comment by lachlanjc** [comment]
I’d love for this to be modeled after the reaction pages on Scrapbook—make a tag page that filters the events, then link to it with little `<Badge>`s on the bottom of the events descriptions. I don’t think we need filtering on the main page since there’s never more than like 5 events there.
